levels:
  binge: 
    value: 20002
    colour: white
  bingedebug: 
    value: 20001
    colour: cyan

appenders:
  console:
    type: console
    layout:
      type: pattern
      pattern: '%[[%d{ISO8601}][%p %c] %z (%f{3} %l:%o)%] %m'
  trace:
    type: dateFile
    filename: logs/app-access.log
    pattern: yyyy-MM-dd
    compress: true
    layout:
      type: pattern
      pattern: '[%d{ISO8601}][%p %c] %z (%f{3} %l:%o) %m'
  http:
    type: logLevelFilter
    appender: trace
    level: trace
    maxLevel: trace
  info:
    type: dateFile
    filename: logs/app-info.log
    pattern: yyyy-MM-dd
    compress: true
    layout:
      type: pattern
      pattern: '[%d{ISO8601}][%p %c] %z (%f{3} %l:%o) %m'
  binge:
    type: dateFile
    filename: logs/app-binge.log
    pattern: yyyy-MM-dd
    compress: true
    layout:
      type: pattern
      pattern: '[%d{ISO8601}][%p %c] %z (%f{3} %l:%o) %m'
  bingedebug:
    type: dateFile
    filename: logs/app-binge-debug.log
    pattern: yyyy-MM-dd
    compress: true
    layout:
      type: pattern
      pattern: '[%d{ISO8601}][%p %c] %z (%f{3} %l:%o) %m'
  debug:
    type: dateFile
    filename: logs/app-debug.log
    pattern: yyyy-MM-dd
    compress: true
    layout:
      type: pattern
      pattern: '[%d{ISO8601}][%p %c] %z (%f{3} %l:%o) %m'
  infoFilter:
    type: logLevelFilter
    appender: info
    level: info
    maxLevel: info
  bingeFilter:
    type: logLevelFilter
    appender: binge
    level: binge
    maxLevel: binge
  bingedebugFilter:
    type: logLevelFilter
    appender: bingedebug
    level: bingedebug
    maxLevel: bingedebug
  debugFilter:
    type: logLevelFilter
    appender: debug
    level: debug
    maxLevel: debug
  error:
    type: dateFile
    filename: logs/app-error.log
    pattern: yyyy-MM-dd
    compress: true
    layout:
      type: pattern
      pattern: '[%d{ISO8601}][%p %c] %z (%f{3} %l:%o) %m'
  minError:
    type: logLevelFilter
    appender: error
    level: error
categories:
  default:
    enableCallStack: true
    appenders:
      - console
      - http
      - infoFilter
      - debugFilter
      - minError
      - bingedebugFilter
      - bingeFilter
    level: info